### ISSUE TITLE
is it ratted?

### ISSUE THREAD

**Issue by uhabsdv** [lorozin/phobos-1.6-9-leak-without-nuke-maed-#8]
seems fake, theres only ever odd numbers, all of them have rats, what makes this one stand out?

**Comment by uhabsdv** [comment]
im not gonna dare to even download it until i know its real

**Comment by PeterPePem** [comment]
its not ratted, but its not an official leak, thats just a phobos 1.9.0 skid made by SomeSadKid_#4699

**Comment by pwn3r1** [comment]
yes its going to steal all of your 420TB of cp
